#! /bin/bash
api_host=localhost:9000/v1
# Create a new repo
curl -X POST -d "path=test&repo_name=test_repo&bare=false" $api_host/repos/
# Show a repo.
curl -X GET -d "path=test&repo_name=test_repo" $api_host/repos/

cd ~/gitcafe/test/test_repo
touch readme
git add .
git commit -m 'add readme'
git br feature
id=$(git show | grep commit)
# Show all branches.
curl -X GET -d "path=test&repo_name=test_repo" $api_host/v1/repos/branches
# List commits
curl -X GET -d "path=test&repo_name=test_repo&branch=master" $api_host/commits
# Show commit info
curl -X GET -d "id=${id#commit}" $api_host/commits/test/test_repo
# Fork a repo
curl -X POST -d "fork_path=fork" $api_host/repos/test/test_repo/fork_bare
# Delete a repo
curl -X DELETE -d "path=test&repo_name=test_repo" $api_host/repos/
# 清理工作
rm -rf ~/gitcafe/fork/test_repo.git